#+TITLE: Group 17: Assignment 1: Pacman.

Members: Lars Blütecher Holter, Lillian Alice Wangerud, Matthias David Greeven

* Introduction

	We made Pacman with openGL. 

	You move the character around with your arrow keys when you've launched the program
	(Up, Down, Left and Right).

	The game will end when you collect all the pellets, and all the sprites on screen will stop.

	How to run the program:
	Clone the repository from Github.
	Generate the CMake list when the files have finished loading in.

	(Should the program fail to load / Cmake list fail to generate, try the following command in
	your GIT command line:
	$ git submodule update --init --recursive
	)
	
	Launch the program via the Pacman.exe file, and enjoy :)

	NOTE:

	We discovered an issue on the 20th November 2021, that our method of generating spherical pellets only works
	on AMD GPU's, not NVIDIA GPU's. This is a problem that is out of our control due to hardware differences on
	our workstations. Likewise, our fullscreen application / hotkey only works on NVIDIA GPU's, not AMD GPU's.